[package]
name = "sw-mc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.27", features = ["serialize"] }

[dev-dependencies]
pretty_assertions = "1.3"
